# spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 2222

#
#
#logging:
#  level:
#    root: info
#    com.mybatis: DEBUG
#    org:
#      springframework:
#        data: debug
#        rest: debug
#        security: debug
#        hibernate.SQL: debug
#
#    com:
#      eunmi:
#        calendar:
#          MembersRepository: debug
#
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:33336/calendar_db?autoReconnect=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT LAST_INSERT_ID(NULL)
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      max-lifetime: 3000000
      minimum-idle: 5
      idle-timeout: 600000
  security:
    user:
      password: user
      name: user